name: Plugin asset/readme update
on:
    push:
        branches:
            - master
jobs:
    master:
        name: Push to master
        runs-on: ubuntu-18.04
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v2
            -   name: Install dependencies
                uses: php-actions/composer@v5
                with:
                    php_version: 7.1
                    version: 1
                    dev: no
            -   name: Install npm dependencies
                run: |
                    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
                    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
                    sudo apt update && sudo apt install nodejs-dev node-gyp libssl1.0-dev yarn
                    yarn --version
                    yarn && yarn run build
                    rm -rf node_modules
            -   name: WordPress.org plugin asset/readme update
                uses: 10up/action-wordpress-plugin-asset-update@458ceae
                env:
                    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                    SLUG: uploadcare
