name: Deploy to WordPress.org
on:
    push
#    push:
#        tags:
#            - "*"
jobs:
    tag:
        name: Upload Plugin to WP SVN
        runs-on: ubuntu-18.04
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v2
            -   name: Install dependencies
                uses: php-actions/composer@v5
                with:
                    php_version: 7.1
                    dev: no
            -   name: Install npm dependencies
                run: |
                    curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
                    curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg > /dev/null
                    echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
                    sudo apt-get update && sudo apt-get install -y gcc g++ make build-essential nodejs node-gyp libssl1.0-dev yarn
                    yarn --version
                    yarn && yarn run build
                    rm -rf node_modules
            -   name: Upload Action Artifact
                uses: actions/upload-artifact@v1
                with:
                    name: uploadcare-wp
                    path: .
#            -   name: WordPress Plugin Deploy
#                uses: 10up/action-wordpress-plugin-deploy@98923950204e68db278a958aa8b71e3b07904140
#                env:
#                    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
#                    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
#                    SLUG: uploadcare
