name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: Upload Plugin to WP SVN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get update
          sudo apt install -y curl php5.6-cli
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer install
      - name: Upload Action Artifact
        uses: actions/upload-artifact@v1
        with:
          name: uploadcare-wp
          path: .
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@9892395
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: uploadcare
