name: Deploy to WordPress.org
on:
    push:
        tags:
            - "*"
jobs:
    tag:
        name: Upload Plugin to WP SVN
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v2
            -   name: Install dependencies
                shell: bash
                run: |
                    sudo apt-get update
                    sudo apt-get install software-properties-common
                    sudo add-apt-repository ppa:ondrej/php
                    sudo apt-get update
                    sudo apt install -y curl php5.6-cli nodejs-dev node-gyp libssl1.0-dev npm
                    curl -sS https://getcomposer.org/installer | php -- --install-dir=/tmp --filename=composer
                    /tmp/composer install --no-dev
            -   name: Install npm dependencies
                run: |
                    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
                    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
                    sudo apt update && sudo apt install nodejs-dev node-gyp libssl1.0-dev yarn
                    yarn --version
                    yarn && yarn run build
                    rm -rf node_modules
                    auth_header="$(git config --local --get http.https://github.com/.extraheader)"
                    git submodule sync --recursive
                    git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
            -   name: Upload Action Artifact
                uses: actions/upload-artifact@v1
                with:
                    name: uploadcare-wp
                    path: .
            -   name: WordPress Plugin Deploy
                uses: 10up/action-wordpress-plugin-deploy@9892395
                env:
                    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                    SLUG: uploadcare
